[package]
name = "tmux-op"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow = "1.0.93"
dirs = "5.0.1"
ignore = "0.4.23"
rayon = "1.10.0"
serde = {version = "1.0.215", features = ["derive"]}
serde_json = "1.0.133"
