[workspace]
resolver = "2"
members = [
    "crates/apps/*",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Dexxiez <toby@boulton.net.au>"]


[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = 3
